<?php

return [
    "eventName" => "IDEAS 2024",
    "eventLocation" => "Expo Center Karachi",
    "eventDate" => "19-22 November 2024",
    "para1" => "The Defence Export Promotion Organization team welcome you for the International Defence Exhibition and Seminar IDEAS 2024. Please confirm your attendance by creating account / Login ID on our Online Delegation System at www.delegation.ideaspakistan.gov.pk. Your Activation Code is given below:- ",
    // "para2" => "",
    // , along with an “expiry date” and “login ID”.",
    "para3" => "The activation code must be entered before the expiry date for you to gain access to our online system.",
    "para4" => "The registration on Delegation System offers comprehensive support during participation in IDEAS 2024 for following:- ",
    "li1" => "Visa application by submitting necessary documents as per Govt of Pakistan policy.",
    "li2" => "Arrival / departure protocols.",
    "li3" => "Interpretation / liaison / Scheduling of side meetings.",
    "li4" => "Hospitality services including room booking, cab hiring, guided tours etc.",
    "li5" => "Confirmation of invitation / registration for planned events of IDEAS 2024.",
    "li6" => "Delegate Registration.",
    "li7" => "Downloading / printing of IDEAS e-badge",
    "heading2" => "Here's How to Get Started:",
    // "li6" => "Go to “IDEAS Delegation Online” for account login and activation at:",
    "subli7" => "www.delegation.ideaspakistan.gov.pk",
    "subli8" => "www.delegation.com.pk",
    // "li7" => "Follow the account creation process, including email verification via OTP (One-Time Password).",
    "li8" => "Upon successful verification, click on the activation button and enter your ID, Password, and OTP.",
    "li9" => "Enter the provided activation code to activate your delegation.",
    "li10" => "Provide complete your required “user login” account information and click “Submit”. After is successful submitted your registration information, then you can access login page to login Delegation Online using “login name” and “password”.",
    "li11" => "At once you are created your login account then will not need to create any other account or registration.",
    "li12" => "For more information, access the “Quick Start Guide for Delegation” located on the login page under the “top” menu. To access the “User’s Guide” login to online delegation handling system and click on User’s Guide PDF” in dashboard page.",
    "heading3" => "How to Regret your Invitation?",
    "li13" => "Go to “IDEAS Delegation Online System” for regretted this your invitation if you not want to participant on International Defence Exhibition and Seminar 2022 (IDEAS 2022).",
    "li14" => "Click on “Regretted” button in login page.",
    "li15" => "Enter your account activation information and the click submit.",
    "li16" => "(Note: once you regretted your invitation then you cannot activate or access your account again).",
    "heading4" => "How to Print your e-Badge?",
    "li17" => "Go to “IDEAS Delegation Online” for account access at;",
    "li18" => "www.delegation.ideaspakistan.gov.pk",
    "li19" => "www.delegation.com.pk",
    "li20" => "Click e-Badge button on each your delegate information table, and print e-badge using A4 size printers.",
    "li21" => "E-Badge document is barcode protected with your unique identification to scan your security clearance and official internal process. Please do must ensure that e-Badge you have printed with barcode on e-badge printed paper.",
    "li22" => "Important Note:",
    "li23" => "If you have more than one delegate, you can enter that information with “Add New” and enter your required information and save.",
    "li24" => "For your participation confirmation on IDEAS 2022, you will need your e- Badge paper print along with further required documents at your “Arrival” in Pakistan. Please bring your e-Badge print copy and show our Airport Welcome Desk or assigned receiving officer.",
    "airportCode" => "AP73177781",
    "carCode" => "CA84288892"

];
