<?php

return [
    "eventName" => "IDEAS 2024",
    "para1" => "Defence Export Promotion Organization team is pleased to provide you on Invitation for International Defence Exhibition and Seminar 2024 (IDEAS 2024).",
    "para2" => "You will need a Login ID and “Activation Code” to confirm your invitation response and register your delegate team information on Delegation Online System. The activation code is listed below.",
    // , along with an “expiry date” and “login ID”.",
    "para3" => "The activation code must be entered before the expiry date for you to gain access to our online system.",
    "para4" => "Delegation Online System for IDEAS 2024 can help you support your participation and confirmation by providing;",
    "li1" => "Access to your Invitation confirmation and update your information.",
    "li2" => "Access to insert your delegate / group of delegates and other information",
    "li3" => "Access to provide your delegate “VISA” process & other required documentation, and approval.",
    "li4" => "Access to your “arrival” & “departure” Information.",
    "heading2" => "Here’s how to get started",
    "li5" => "Access a computer with an internet connection and a web browser.  (Like, Google Chrome, Firefox is recommended).",
    "li6" => "Go to “DHS” for account signup/login and activation at:",
    // "li6" => "Go to “IDEAS Delegation Online” for account login and activation at:",
    "subli7" => "www.dhs.ideaspakistan.gov.pk",
    "subli8" => "www.delegation.com.pk",
    "li7" => "First, you need to go to www.delegation.ideaspakistan.gov.pk. After that, you'll need to create an account. During the account creation process, an OTP (One-Time Password) will be sent to your email for email verification. After verifying your email, you'll need to click on the activation button. Then, you'll need to enter your ID and Password along with the OTP. After that, you'll be logged in. Then, you'll need to enter the provided code to activate your delegation.",
    "li8" => "You will need to enter the “login ID” and “activation code” exactly as show in this letter.",
    "li9" => "Enter your account activation information and then click “Submit”. After successfully completed your activation you will need created a user login account to login and access “Delegation Online System”",
    "li10" => "Provide complete your required “user login” account information and click “Submit”. After is successful submitted your registration information, then you can access login page to login Delegation Online using “login name” and “password”.",
    "li11" => "At once you are created your login account then will not need to create any other account or registration.",
    "li12" => "For more information, access the “Quick Start Guide for Delegation” located on the login page under the “top” menu. To access the “User’s Guide” login to online delegation handling system and click on User’s Guide PDF” in dashboard page.",
    "heading3" => "How to Regret your Invitation?",
    "li13" => "Go to “IDEAS Delegation Online System” for regretted this your invitation if you not want to participant on International Defence Exhibition and Seminar 2022 (IDEAS 2022).",
    "li14" => "Click on “Regretted” button in login page.",
    "li15" => "Enter your account activation information and the click submit.",
    "li16" => "(Note: once you regretted your invitation then you cannot activate or access your account again).",
    "heading4" => "How to Print your e-Badge?",
    "li17" => "Go to “IDEAS Delegation Online” for account access at;",
    "li18" => "www.delegation.ideaspakistan.gov.pk",
    "li19" => "www.delegation.com.pk",
    "li20" => "Click e-Badge button on each your delegate information table, and print e-badge using A4 size printers.",
    "li21" => "E-Badge document is barcode protected with your unique identification to scan your security clearance and official internal process. Please do must ensure that e-Badge you have printed with barcode on e-badge printed paper.",
    "li22" => "Important Note:",
    "li23" => "If you have more than one delegate, you can enter that information with “Add New” and enter your required information and save.",
    "li24" => "For your participation confirmation on IDEAS 2022, you will need your e- Badge paper print along with further required documents at your “Arrival” in Pakistan. Please bring your e-Badge print copy and show our Airport Welcome Desk or assigned receiving officer.",
    "airportCode"=>"AP73177781"

];
